[package]
name = "algorithms"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15.3"
rand = "0.8"
rand_distr = "0.4"
ascii_converter = "0.3.0"
polynomial = "0.2.6"
rustfft = "6.2.0"
lll-rs = "0.2.0"
num-bigint = "0.4.6"
rug = "1.26.1"
